///Users/oriolesinski/analytics-automation/packages/analytics-platform/src/app/onboarding/deploy/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';

export async function POST(request: NextRequest) {
  try {
    const { 
      repoOwner, 
      repoName, 
      trackerCode, 
      providerCode, 
      appKey,
      autoMerge = false 
    } = await request.json();

    // Get GitHub token from session/cookies (set during auth)
    const githubToken = request.cookies.get('github_token')?.value;
    
    if (!githubToken) {
      return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
    }

    const octokit = new Octokit({ auth: githubToken });

    // 1. Get the default branch
    const { data: repo } = await octokit.repos.get({
      owner: repoOwner,
      repo: repoName
    });
    const baseBranch = repo.default_branch;

    // 2. Get the latest commit SHA from base branch
    const { data: ref } = await octokit.git.getRef({
      owner: repoOwner,
      repo: repoName,
      ref: `heads/${baseBranch}`
    });
    const baseSha = ref.object.sha;

    // 3. Create a new branch
    const branchName = `analytics-integration-${Date.now()}`;
    await octokit.git.createRef({
      owner: repoOwner,
      repo: repoName,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    });

    // 4. Create/update tracker.js file
    const trackerPath = 'public/tracker.js';
    let trackerSha;
    
    try {
      const { data: existingFile } = await octokit.repos.getContent({
        owner: repoOwner,
        repo: repoName,
        path: trackerPath,
        ref: baseBranch
      });
      trackerSha = Array.isArray(existingFile) ? undefined : existingFile.sha;
    } catch (e) {
      // File doesn't exist, that's OK
    }

    await octokit.repos.createOrUpdateFileContents({
      owner: repoOwner,
      repo: repoName,
      path: trackerPath,
      message: 'Add analytics tracker',
      content: Buffer.from(trackerCode).toString('base64'),
      branch: branchName,
      sha: trackerSha // Required if updating existing file
    });

    // 5. Create/update analytics provider
    const providerPath = 'src/components/AnalyticsProvider.tsx';
    let providerSha;
    
    try {
      const { data: existingFile } = await octokit.repos.getContent({
        owner: repoOwner,
        repo: repoName,
        path: providerPath,
        ref: baseBranch
      });
      providerSha = Array.isArray(existingFile) ? undefined : existingFile.sha;
    } catch (e) {
      // File doesn't exist
    }

    await octokit.repos.createOrUpdateFileContents({
      owner: repoOwner,
      repo: repoName,
      path: providerPath,
      message: 'Add analytics provider component',
      content: Buffer.from(providerCode).toString('base64'),
      branch: branchName,
      sha: providerSha
    });

    // 6. Create Pull Request
    const { data: pr } = await octokit.pulls.create({
      owner: repoOwner,
      repo: repoName,
      title: '🎯 Add Analytics Tracking',
      head: branchName,
      base: baseBranch,
      body: `## Analytics Integration

This PR adds analytics tracking to your application.

### What's included:
- ✅ Analytics tracker script (\`/tracker.js\`)
- ✅ React Analytics Provider component
- ✅ Auto-configured with app key: \`${appKey}\`

### Installation:
1. Add \`<script src="/tracker.js"></script>\` to your HTML
2. Wrap your app with \`<AnalyticsProvider>\`

### Features:
- 🤖 AI-powered event detection
- 🔑 Persistent user tracking (8-10 digit IDs)
- 📊 5 event types (PAGE_VIEW, BUTTON_CLICK, etc.)
- 🚀 Zero configuration required

---
*Generated by Analytics Platform*`
    });

    // 7. Auto-merge if requested and user has permissions
    if (autoMerge) {
      try {
        await octokit.pulls.merge({
          owner: repoOwner,
          repo: repoName,
          pull_number: pr.number,
          merge_method: 'squash'
        });
        
        // Delete branch after merge
        await octokit.git.deleteRef({
          owner: repoOwner,
          repo: repoName,
          ref: `heads/${branchName}`
        });
      } catch (mergeError) {
        console.log('Auto-merge failed (may need admin rights):', mergeError);
        // Not a critical error - PR is still created
      }
    }

    return NextResponse.json({
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: branchName
    });

  } catch (error) {
    console.error('Deploy error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Deployment failed' },
      { status: 500 }
    );
  }
}