// packages/analytics-platform/src/app/api/deploy/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { repoOwner, repoName, trackerCode, providerCode, appKey, autoMerge } = body;

        // Get token from cookie
        const token = request.cookies.get('github_token')?.value;

        if (!token) {
            return NextResponse.json(
                { error: 'Not authenticated' },
                { status: 401 }
            );
        }

        const octokit = new Octokit({ auth: token });

        console.log(`Creating PR for ${repoOwner}/${repoName}...`);

        try {
            // Step 1: Get the default branch
            const { data: repo } = await octokit.rest.repos.get({
                owner: repoOwner,
                repo: repoName
            });
            const defaultBranch = repo.default_branch || 'main';

            // Step 2: Get the latest commit SHA from default branch
            const { data: ref } = await octokit.rest.git.getRef({
                owner: repoOwner,
                repo: repoName,
                ref: `heads/${defaultBranch}`
            });
            const baseSha = ref.object.sha;

            // Step 3: Create a new branch
            const branchName = `analytics-integration-${Date.now()}`;
            await octokit.rest.git.createRef({
                owner: repoOwner,
                repo: repoName,
                ref: `refs/heads/${branchName}`,
                sha: baseSha
            });

            console.log(`Created branch: ${branchName}`);

            // Step 4: Get the base tree
            const { data: baseCommit } = await octokit.rest.git.getCommit({
                owner: repoOwner,
                repo: repoName,
                commit_sha: baseSha
            });
            const baseTreeSha = baseCommit.tree.sha;

            // Step 5: Create blobs for our files
            const trackerBlob = await octokit.rest.git.createBlob({
                owner: repoOwner,
                repo: repoName,
                content: Buffer.from(trackerCode).toString('base64'),
                encoding: 'base64'
            });

            const providerBlob = await octokit.rest.git.createBlob({
                owner: repoOwner,
                repo: repoName,
                content: Buffer.from(providerCode).toString('base64'),
                encoding: 'base64'
            });

            // Step 6: Create a new tree with our files
            const { data: newTree } = await octokit.rest.git.createTree({
                owner: repoOwner,
                repo: repoName,
                base_tree: baseTreeSha,
                tree: [
                    {
                        path: 'public/tracker.js',
                        mode: '100644',
                        type: 'blob',
                        sha: trackerBlob.data.sha
                    },
                    {
                        path: 'app/components/analytics-provider.tsx',
                        mode: '100644',
                        type: 'blob',
                        sha: providerBlob.data.sha
                    }
                ]
            });

            // Step 7: Create a new commit
            const { data: newCommit } = await octokit.rest.git.createCommit({
                owner: repoOwner,
                repo: repoName,
                message: '✨ Add Analytics Tracking Integration\n\nThis PR adds comprehensive analytics tracking to the application.',
                tree: newTree.sha,
                parents: [baseSha]
            });

            // Step 8: Update the branch reference
            await octokit.rest.git.updateRef({
                owner: repoOwner,
                repo: repoName,
                ref: `heads/${branchName}`,
                sha: newCommit.sha
            });

            // Step 9: Create the Pull Request
            const prBody = `
## 🎯 Analytics Integration

This PR adds comprehensive analytics tracking to your application.

### 📊 What's Included

- **Event Tracking**: Automatic tracking of user interactions
- **Page Views**: Track navigation and page visits
- **User Engagement**: Monitor clicks, scrolls, and form submissions
- **Custom Events**: Extensible framework for custom tracking

### 📁 Files Added

- \`public/tracker.js\` - Core analytics tracking script
- \`app/components/analytics-provider.tsx\` - React provider component

### 🚀 Next Steps

1. Review the generated tracking configuration
2. Merge this PR to enable analytics
3. View real-time data in your [Analytics Dashboard](http://localhost:3002/dashboard?app=${appKey})

### 🔑 App Key
\`${appKey}\`

---
*Generated by Analytics Platform*
      `;

            const { data: pr } = await octokit.rest.pulls.create({
                owner: repoOwner,
                repo: repoName,
                title: '✨ Add Analytics Tracking',
                body: prBody,
                head: branchName,
                base: defaultBranch
            });

            console.log(`Created PR: ${pr.html_url}`);

            // Step 10: Auto-merge if requested
            let merged = false;
            if (autoMerge) {
                try {
                    // First, approve the PR if possible (requires appropriate permissions)
                    try {
                        await octokit.rest.pulls.createReview({
                            owner: repoOwner,
                            repo: repoName,
                            pull_number: pr.number,
                            event: 'APPROVE'
                        });
                    } catch (approveError) {
                        console.log('Could not auto-approve (normal for own PRs)');
                    }

                    // Try to merge
                    await octokit.rest.pulls.merge({
                        owner: repoOwner,
                        repo: repoName,
                        pull_number: pr.number,
                        merge_method: 'squash'
                    });
                    merged = true;
                    console.log('PR auto-merged successfully');
                } catch (mergeError: any) {
                    console.error('Auto-merge failed:', mergeError.message);
                    // Continue without auto-merge
                }
            }

            // Step 11: Update app status in database
            await fetch('http://localhost:8082/apps/update-status', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    app_key: appKey,
                    setup_status: merged ? 'deployed' : 'pr_created',
                    pr_url: pr.html_url
                })
            });

            return NextResponse.json({
                success: true,
                prUrl: pr.html_url,
                prNumber: pr.number,
                merged,
                branch: branchName
            });

        } catch (githubError: any) {
            console.error('GitHub API error:', githubError);

            if (githubError.status === 404) {
                return NextResponse.json(
                    { error: 'Repository not found or you lack access' },
                    { status: 404 }
                );
            }

            if (githubError.status === 403) {
                return NextResponse.json(
                    { error: 'Insufficient permissions to create PR. Ensure token has "repo" scope.' },
                    { status: 403 }
                );
            }

            throw githubError;
        }

    } catch (error: any) {
        console.error('Deployment error:', error);
        return NextResponse.json(
            {
                error: 'Failed to create pull request',
                details: error.message
            },
            { status: 500 }
        );
    }
}