import RouteListener from './components/RouteListener';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<RouteListener />

        {children}
      </body>
    </html>
  );
}
<RouteListener />
// AA_INSERT_GUARD: demo-next/src/app/layout.tsx :: PGJvZHk+

import RouteListener from './components/RouteListener';
// AA_INSERT_GUARD: demo-next/src/app/layout.tsx :: aW1wb3J0IFJlYWN0

